config/routes.rb
Rails.application.routes.draw do

  namespace :api do
    namespace :v1 do
      resources :users, only: [] do
      resources :posts, only: [:index] do
        resources :comments, only: [:index, :create]
      end
    end
    end
  end

  devise_for :users

  root 'users#index'
  
  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :new, :create, :show, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create, :destroy]
    end
  end
  
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :likes, class_name: 'Like', foreign_key: 'post_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id'

  validates :title, presence: true, length: { maximum: 250 }

  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0 }

  after_create :update_user_posts_counter

  def five_recent_comments
    comments.includes(:user).order(created_at: :desc).limit(5)
  end

  private

  def update_user_posts_counter
    author.increment!(:posts_counter)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ApplicationController
  def index
    user = User.find(params[:user_id])
    posts = user.posts

    if posts.present?
      render json: { success: true, message: 'Posts retrieved successfully', posts: posts }
    else
      render json: { success: false, message: 'No posts found for the user', status: :not_found }
    end
  rescue ActiveRecord::RecordNotFound
    render json: { error: 'User not found', status: :not_found }
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @post = @user.Post

    render :index
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])

    render :show
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.find(params[:user_id])
    @post = Post.includes(:author, :comments).where(author_id: params[:user_id])

    render :index
  end

  def show
    @user = User.find(params[:user_id])
    @post = @user.posts.find(params[:id])

    if @post
      @comment = Comment.new
      @like = Like.new
    end

    @comment = Comment.new
    @comments = @post.comments

    render :show
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)
    @post.comments_counter = 0
    @post.likes_counter = 0

    if @post.save

      redirect_to user_posts_path, notice: 'Post saved successfully'
    else
      flash.now[:error] = @post.errors.full_messages.to_sentence
      render :new
    end
  end

  def destroy
    @post = current_user.posts.find(params[:id])

    if @post.destroy
      redirect_to user_posts_path(current_user, @post), notice: 'Post was successfully deleted'
    else
      p @post.errors.full_messages
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/posts/index.html.erb
<section class="postsindex">
<h1>All posts</h1>
<div class='post_index'>
  <%= render partial: 'partials/user', locals: { user: @user } %>
  <br>
  <% Post.includes(:comments).each do |post| %>
    <%= render partial: 'partials/post', locals: { post: post } %>
    
    <% commentp = post.five_recent_comments %>    
    <%= render partial: 'partials/comment', locals: { comment: commentp } %>
    
  <% end %>

  <button type="button" class="btn btn-outline-dark">PAGINATION</button>
</div>

</section>

app/views/posts/new.html.erb
<section class='create_new_post'>
<h1>Create a new post</h1>
<%= form_with model: @post, url: user_posts_path(@user), method: :post do |f| %>

  <div class='post_input'>
    <div class='input_field'>
      <%= f.label :title %>
      <%= f.text_field :title, required: true, class: 'post_title', placeholder: 'Add title here' %>
    </div>
    <div class='input_field'>
      <%= f.label :text %>
      <%= f.text_area :text, required: true, class: 'post_text', placeholder: 'Write your text ...' %>
    </div>
    <br>
    <%= f.submit 'Create Post', class: 'login_signup_btn' %>
  </div>

  <% if flash[:error] %>
  <div class=''error-message>
    <%= flash[:error] %>
    
  </div>
  <% end %>
<% end %>


</section>

app/views/posts/show.html.erb
<div class="postshow">

<h1>Post details</h1>
<div class='post_detail'>
 
  <div class='pos'>
   <div class='post_det'>
     <div>Post <%= @post.id %> by <%= @post.author.Name %></div>
     <div class="post_like_comment">
       <div>Comments: <%=@post.comments_counter %></div>
       <div class='like '>Likes: <%=@post.likes_counter %></div>
     </div>
   </div>
   <br>
   <div class='post_text'>
     <%= @post.text %>
  </div>  

  <br>

</div>

<br>

  <% if can? :destroy, @post %>
    <%= link_to 'DELETE POST', polymorphic_url([@post.author, @post]), data: {
      turbo_method: :delete,
      turbo_confirm: "Are you sure?"} %>
    <% end %>

  <%= form_with url: user_post_likes_path(current_user, @post), method: :post do |form| %>
    <%= form.hidden_field :authenticity_token, value: form_authenticity_token %>
    <%= form.submit "Add Likes", class: 'btn_add_likes' %>
  <% end %>
  
  <% commentpost = @post.comments %>
  <%= render partial: 'partials/comment', locals: { comment: commentpost }%>

  <a href='/users/<%= @user.id %>/posts/<%= @post.id %>/comments/new' class='post_cont'>Add Comment</a>
  <a href='/users/<%= @user.id %>/posts/new' class = 'create_post'>CREATE POST</a>
  